name: "Advance"
concurrency: update-advance
on:
  schedule:
    - cron: '30 */1 * * *'
  workflow_dispatch:
jobs:
  advance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup-nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-config: |
          extra-substituters = https://nixpkgs-wayland.cachix.org
          extra-trusted-public-keys = nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA=
    - name: prepare
      run: nix develop -c .github/init
    - name: advance
      env:
        CACHIX_SIGNING_KEY_NIXPKGS_WAYLAND: "${{ secrets.cachix_signing_key_nixpkgs_wayland }}"
      run: nix develop -c ./main.nu advance
