name: "Update"
concurrency: update-advance
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup-nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: prepare
      run: nix develop --accept-flake-config -c .github/init
    - name: update
      env:
        CACHIX_SIGNING_KEY_NIXPKGS_WAYLAND: "${{ secrets.cachix_signing_key_nixpkgs_wayland }}"
      run: nix develop --accept-flake-config -c ./main.nu update
